### PR TITLE
Add Another Heading to Docs

### PR DESCRIPTION
**Pull request by LanikSJ**
## Description
Add Another Heading to Docs

## Related Issue
Missing Heading in Windows Instructions

## Motivation and Context
Docs Cleanup

## How Has This Been Tested?
Travis CI

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [x] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by krazyito65** [comment]
can you update one thing before you merge

```
Revert to Light Mode (SNAP)
./snap-slack-dark-mode.sh -light
```

should be 
```
Revert to Light Mode (SNAP)
./snap-slack-dark-mode.sh -l
```

**Comment by LanikSJ** [comment]
Okay no problem, it's done.

**Comment by krazyito65** [comment]
Also windows has `-LightMode` haha

**Comment by LanikSJ** [comment]
Thank you added that as well.

**Pull request merged**
